// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: author.sql

package bloggi_db

import (
	"context"
)

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, description, github, website, linkedin FROM public.author
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Github,
		&i.Website,
		&i.Linkedin,
	)
	return i, err
}
