// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bloggi_db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PostBlockType string

const (
	PostBlockTypeText        PostBlockType = "text"
	PostBlockTypeMarkdown    PostBlockType = "markdown"
	PostBlockTypeMedia       PostBlockType = "media"
	PostBlockTypeCode        PostBlockType = "code"
	PostBlockTypeHtml        PostBlockType = "html"
	PostBlockTypeCardContent PostBlockType = "card_content"
	PostBlockTypeEmbed       PostBlockType = "embed"
)

func (e *PostBlockType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostBlockType(s)
	case string:
		*e = PostBlockType(s)
	default:
		return fmt.Errorf("unsupported scan type for PostBlockType: %T", src)
	}
	return nil
}

type NullPostBlockType struct {
	PostBlockType PostBlockType
	Valid         bool // Valid is true if PostBlockType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostBlockType) Scan(value interface{}) error {
	if value == nil {
		ns.PostBlockType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostBlockType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostBlockType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostBlockType), nil
}

type Author struct {
	ID          string
	Name        string
	Description pgtype.Text
	Github      pgtype.Text
	Website     pgtype.Text
	Linkedin    pgtype.Text
}

type Post struct {
	ID           string
	Title        string
	AuthoredDate pgtype.Timestamptz
	AuthorID     string
	Published    bool
	VectorText   interface{}
}

type PostBlock struct {
	ID           string
	BlockOrdinal int32
	BlockType    PostBlockType
	PostID       string
	ContentData  []byte
	RevisionID   string
	VectorText   interface{}
}

type PostRevision struct {
	ID           string
	PostID       string
	Published    bool
	ChangeLog    pgtype.Text
	RevisionDate pgtype.Timestamptz
	PublicID     pgtype.Int4
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
