// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package bloggi_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO public.post (id, title, authored_date, author_id, published)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, authored_date, author_id, published, vector_text
`

type CreatePostParams struct {
	ID           string
	Title        string
	AuthoredDate pgtype.Timestamptz
	AuthorID     string
	Published    bool
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.AuthoredDate,
		arg.AuthorID,
		arg.Published,
	)
	return err
}
