// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_revision.sql

package bloggi_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRevision = `-- name: CreateRevision :exec
INSERT INTO public.post_revision (id, post_id, published, change_log, revision_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, published, change_log, revision_date, public_id
`

type CreateRevisionParams struct {
	ID           string
	PostID       string
	Published    bool
	ChangeLog    pgtype.Text
	RevisionDate pgtype.Timestamptz
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.Exec(ctx, createRevision,
		arg.ID,
		arg.PostID,
		arg.Published,
		arg.ChangeLog,
		arg.RevisionDate,
	)
	return err
}
