/**
 * OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetFsList200ResponseChildrenInner { 
    type: GetFsList200ResponseChildrenInner.TypeEnum;
    name: string;
}
export namespace GetFsList200ResponseChildrenInner {
    export type TypeEnum = 'file' | 'directory';
    export const TypeEnum = {
        File: 'file' as TypeEnum,
        Directory: 'directory' as TypeEnum
    };
}


