/**
 * OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFsList200ResponseChildrenInner } from './getFsList200ResponseChildrenInner';


export interface GetFsList200Response { 
    type: GetFsList200Response.TypeEnum;
    name: string;
    children: Array<GetFsList200ResponseChildrenInner>;
}
export namespace GetFsList200Response {
    export type TypeEnum = 'directory';
    export const TypeEnum = {
        Directory: 'directory' as TypeEnum
    };
}


