/**
 * OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetNowPlaying200Response { 
    title: string;
    artist: string;
    itemImage: string | null;
    album: string | null;
    albumArt: string | null;
    duration: number;
    totalDuration: number;
    deviceType: string;
    trackType: GetNowPlaying200Response.TrackTypeEnum;
}
export namespace GetNowPlaying200Response {
    export type TrackTypeEnum = 'track' | 'episode' | 'ad' | 'unknown';
    export const TrackTypeEnum = {
        Track: 'track' as TrackTypeEnum,
        Episode: 'episode' as TrackTypeEnum,
        Ad: 'ad' as TrackTypeEnum,
        Unknown: 'unknown' as TrackTypeEnum
    };
}


