/**
 * OpenAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostContactMeRequest { 
    /**
     * Email to send the message to
     */
    email: string;
    /**
     * Message to send
     */
    message: string;
    /**
     * Captcha key
     */
    captchaKey: string;
}

