/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto = {
    Published: 'Published',
    Draft: 'Draft'
} as const;
export type BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto = typeof BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto[keyof typeof BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto];

