/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BloggiBackendApiWebFeaturesPostEndpointsRevisionsListRevisionsListRevisionsRevision { 
    id?: string;
    createdAt?: string;
    revisionNumber?: number;
    key?: string | null;
    isPublished?: boolean;
    isCurrent?: boolean;
    publishedAt?: string | null;
}

