/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type BloggiBackendEditorJSCoreBlockTypes = 'Unknown' | 'Paragraph' | 'Header' | 'Link' | 'Embed' | 'Quote' | 'Code' | 'Table' | 'Warning' | 'InlineCode' | 'List' | 'Image' | 'Math' | 'Button';

export const BloggiBackendEditorJSCoreBlockTypes = {

    Unknown: 'Unknown' as BloggiBackendEditorJSCoreBlockTypes,

    Paragraph: 'Paragraph' as BloggiBackendEditorJSCoreBlockTypes,

    Header: 'Header' as BloggiBackendEditorJSCoreBlockTypes,

    Link: 'Link' as BloggiBackendEditorJSCoreBlockTypes,

    Embed: 'Embed' as BloggiBackendEditorJSCoreBlockTypes,

    Quote: 'Quote' as BloggiBackendEditorJSCoreBlockTypes,

    Code: 'Code' as BloggiBackendEditorJSCoreBlockTypes,

    Table: 'Table' as BloggiBackendEditorJSCoreBlockTypes,

    Warning: 'Warning' as BloggiBackendEditorJSCoreBlockTypes,

    InlineCode: 'InlineCode' as BloggiBackendEditorJSCoreBlockTypes,

    List: 'List' as BloggiBackendEditorJSCoreBlockTypes,

    Image: 'Image' as BloggiBackendEditorJSCoreBlockTypes,

    Math: 'Math' as BloggiBackendEditorJSCoreBlockTypes,

    Button: 'Button' as BloggiBackendEditorJSCoreBlockTypes
};

