/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendApiWebFeaturesPostEndpointsRevisionsListRevisionsListRevisionsRevision } from './bloggiBackendApiWebFeaturesPostEndpointsRevisionsListRevisionsListRevisionsRevision';


export interface BloggiBackendApiWebFeaturesPostEndpointsRevisionsListRevisionsListRevisionsResponse { 
    postId?: string;
    revisions?: Array<BloggiBackendApiWebFeaturesPostEndpointsRevisionsListRevisionsListRevisionsRevision>;
}

