/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostGetPostIncludeProperty = 'Tags' | 'Author';

export const BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostGetPostIncludeProperty = {

    Tags: 'Tags' as BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostGetPostIncludeProperty,

    Author: 'Author' as BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostGetPostIncludeProperty
};

