/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BloggiBackendApiWebFeaturesPostEndpointsPostGetFilesGetFilesFile { 
    fileId?: string;
    name?: string;
    type?: string;
    size?: number;
    hash?: string;
    createdAt?: string;
    updatedAt?: string;
}

