/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendEditorJSCoreModelsOutputData } from './bloggiBackendEditorJSCoreModelsOutputData';


export interface BloggiBackendApiWebFeaturesPostEndpointsPostBlockUpsertPostBlockUpsertPostBlockRequest { 
    editorJsData: BloggiBackendEditorJSCoreModelsOutputData;
}

