/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostResponseAuthor } from './bloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostResponseAuthor';
import { BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto } from './bloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto';
import { BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostTagDto } from './bloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostTagDto';


export interface BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostResponse { 
    id?: string;
    title?: string;
    excerpt?: string | null;
    slug?: string;
    tags?: Array<BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostTagDto>;
    status?: BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto;
    createdAt?: string;
    updatedAt?: string;
    publishedAt?: string | null;
    author?: BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostResponseAuthor | null;
}
export namespace BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostResponse {
}


