/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponse { 
    title?: string | null;
    description?: string | null;
    imageUrl?: string | null;
    favicon?: string | null;
}

