/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaDataImage } from './bloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaDataImage';


export interface BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaData { 
    title?: string | null;
    description?: string | null;
    image?: BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaDataImage | null;
}

