/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BloggiBackendApiWebFeaturesPostEndpointsPostGetMetaGetMetaResponse { 
    postId?: string;
    openGraphTitle?: string | null;
    openGraphDescription?: string | null;
    openGraphImageUrl?: string | null;
    canonicalUrl?: string | null;
    robot?: string;
    schemaOrgJson?: any | null;
    editorVersion?: string;
}

