/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendEditorJSCoreModelsEditorBlock } from './bloggiBackendEditorJSCoreModelsEditorBlock';


export interface BloggiBackendEditorJSCoreModelsOutputData { 
    time: number;
    version: string;
    blocks: Array<BloggiBackendEditorJSCoreModelsEditorBlock>;
}

