/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto = 'Published' | 'Draft';

export const BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto = {

    Published: 'Published' as BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto,

    Draft: 'Draft' as BloggiBackendApiWebFeaturesPostEndpointsPostGetPostGetPostStatusDto
};

