/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaDataImage } from './bloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaDataImage';
import { BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaData } from './bloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaData';


/**
 * @type BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMeta
 * @export
 */
export type BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMeta = BloggiBackendApiWebFeaturesPostEndpointsEditorLinkMetaLinkMetaResponseMetaData;

