/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type BloggiBackendEditorJSCoreBlockTypes = 'Unknown' | 'Header';

export const BloggiBackendEditorJSCoreBlockTypes = {

    Unknown: 'Unknown' as BloggiBackendEditorJSCoreBlockTypes,

    Header: 'Header' as BloggiBackendEditorJSCoreBlockTypes
};

