/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BloggiBackendApiWebFeaturesPostEndpointsPreviewRenderRenderResponseError } from './bloggiBackendApiWebFeaturesPostEndpointsPreviewRenderRenderResponseError';


export interface BloggiBackendApiWebFeaturesPostEndpointsPreviewRenderRenderResponse { 
    html?: string;
    errors?: Array<BloggiBackendApiWebFeaturesPostEndpointsPreviewRenderRenderResponseError>;
}

