/**
 * Bloggi.Backend.Api.Web
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const BloggiBackendEditorJSCoreBlockTypes = {
    Unknown: 'Unknown',
    Paragraph: 'Paragraph',
    Header: 'Header',
    Link: 'Link',
    Embed: 'Embed',
    Quote: 'Quote',
    Code: 'Code',
    Table: 'Table',
    Warning: 'Warning',
    InlineCode: 'InlineCode',
    List: 'List',
    Image: 'Image',
    Math: 'Math',
    Button: 'Button'
} as const;
export type BloggiBackendEditorJSCoreBlockTypes = typeof BloggiBackendEditorJSCoreBlockTypes[keyof typeof BloggiBackendEditorJSCoreBlockTypes];

